{% set name = "onnxslim" %}
{% set version = "0.1.68" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ff1ec2bf61ff10b75e33990b2046c446dec522ba7f0a12b2f984547ff43f9138

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  entry_points:
    - onnxslim = onnxslim.cli:main

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - colorama
    - ml_dtypes
    - onnx
    - packaging
    - python >={{ python_min }}
    - sympy >=1.13.3

test:
  imports:
    - onnxslim
  commands:
    - pip check
    - onnxslim --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/inisis/OnnxSlim
  summary: A Toolkit to Help Optimize Onnx Model
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jeongseok-meta
