{% set name = "onnxslim" %}
{% set version = "0.1.58" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: fbce841d2681260ea28f02c1b61faee9e6fd4d16cb5d5c72e7d98beb6051ac72

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  entry_points:
    - onnxslim = onnxslim.cli:main

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - onnx
    - packaging
    - python >={{ python_min }}
    - sympy

test:
  imports:
    - onnxslim
  commands:
    - pip check
    - onnxslim --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/inisis/OnnxSlim
  summary: A Toolkit to Help Optimize Onnx Model
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jeongseok-meta
