schema_version: 1

context:
  name: onnxslim
  version: "0.1.94"
  python_min: "3.10"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/o/onnxslim/onnxslim-${{ version }}.tar.gz
  sha256: 83a3d428e55a0d1b7db88a4eadf8b1763bc38e8f7e4a48cbe72c5a7bbaf583b3

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - onnxslim = onnxslim.cli:main

requirements:
  host:
    - hatchling
    - pip
    - python ${{ python_min }}.*
  run:
    - colorama
    - ml_dtypes
    - onnx
    - packaging
    - python >=${{ python_min }}
    - sympy >=1.13.3

tests:
  - python:
      imports:
        - onnxslim
      pip_check: true
      python_version: ${{ python_min }}.*
  - script:
      - pip check
      - onnxslim --help
      - python run_test.py
    files:
      recipe:
        - run_test.py
    requirements:
      run:
        - pip
        - python ${{ python_min }}.*

about:
  homepage: https://github.com/inisis/OnnxSlim
  repository: https://github.com/inisis/OnnxSlim
  summary: A Toolkit to Help Optimize Onnx Model
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jeongseok-meta
